name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]
    tags: ["v*"]
  pull_request:

jobs:
  build-with-xk6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest
      - name: Build
        run: make build
      - name: Test
        run: make test

      - name: Build binaries
        if: startsWith(github.ref, 'refs/tags/')
        run: make build-ci
      - name: Release binaries
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          generate_release_notes: true
          files: |
            # List your binary files here
            k6-darwin-amd64-${{ github.ref_name }}
            k6-darwin-arm64-${{ github.ref_name }}
            k6-linux-amd64-${{ github.ref_name }}
            k6-linux-arm64-${{ github.ref_name }}
            k6-window-amd64-${{ github.ref_name }}
            k6-windows-arm64-${{ github.ref_name }}
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            Release created from tag ${{ github.ref }}

